manifest-version = 1

[component]
name = "Slack Message"
version = "1.0.0"

category = "edge-function"
subcategory = "wasm-function"
description = "Edge function component to send Slack messages."
documentation = "https://www.edgee.cloud/docs/components/edge-functions/sendgrid"
repository = "https://github.com/edgee-cloud/slack-message-component"
language = "Rust"
wit-version = "1.0.0"
icon-path = "slack.png"

[component.build]
command = "cargo build --release --target wasm32-wasip2 --target-dir ./target && rm -f ./slack.wasm && mv ./target/wasm32-wasip2/release/slack_message_component.wasm ./slack.wasm"
output_path = "slack.wasm"

[component.settings.webhook_url]
title = "Slack Webhook URL"
type = "string"
required = true
description = "The incoming webhook such as https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX"